version: '3.8'

services:
  nexus:
    image: sonatype/nexus3:3.69.0-java8
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - ./scripts:/scripts
      - ./common/data/nexus-data:/nexus-data
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false
      - NEXUS_ADMIN_PASSWORD=admin123
      - INSTALL4J_ADD_VM_PARAMS=-Xms4g -Xmx8g
    restart: always
    entrypoint: /scripts/system/before/nexus/add_proxy.sh
    healthcheck:
      test: [ "CMD-SHELL", "test -f /scripts/system/before/nexus/.lock" ]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      ambari-env-network:
        ipv4_address: 172.20.0.2
#
#  centos1:
#    image: centos:7.9.2009
#    container_name: centos1
#    hostname: centos1
#    ports:
#      - "85:80"
#      - "22223:22"
#      - "28080:8080"
#      - "16379:6379"
#      - "16380:6380"
#      - "16381:6381"
#      - "16382:6382"
#      - "16383:6383"
#      - "16384:6384"
#      - "12181:2181"
#      - "12345:12345"
#    tty: true
#    privileged: true
#    volumes:
#      - ./scripts:/scripts
#      - ./common/etc/yum.repos.d:/etc/yum.repos.d
#      - ./common/conf:/opt/modules/conf
#      - ./common/data/mvn:/root/.m2
#      - ./common/data/rpm-package:/data/rpm-package
#    entrypoint: /scripts/master.sh
#    depends_on:
#      nexus:
#        condition: service_healthy
#    networks:
#      ambari-env-network:
#        ipv4_address: 172.20.0.3
#
#  centos2:
#    image: centos:7.9.2009
#    container_name: centos2
#    hostname: centos2
#    ports:
#      - "22224:22"
#      - "26379:6379"
#      - "26380:6380"
#      - "26381:6381"
#      - "26382:6382"
#      - "26383:6383"
#      - "26384:6384"
#      - "22181:2181"
#      - "22345:12345"
#    tty: true
#    privileged: true
#    volumes:
#      - ./scripts:/scripts
#      - ./common/etc/yum.repos.d:/etc/yum.repos.d
#      - ./common/conf:/opt/modules/conf
#      - ./common/data/mvn:/root/.m2
#    entrypoint: /scripts/slave.sh
#    depends_on:
#      nexus:
#        condition: service_healthy
#    networks:
#      ambari-env-network:
#        ipv4_address: 172.20.0.4
#
#  centos3:
#    image: centos:7.9.2009
#    container_name: centos3
#    hostname: centos3
#    ports:
#      - "22225:22"
#      - "36379:6379"
#      - "36380:6380"
#      - "36381:6381"
#      - "36382:6382"
#      - "36383:6383"
#      - "36384:6384"
#      - "32181:2181"
#      - "32345:12345"
#    tty: true
#    privileged: true
#    volumes:
#      - ./scripts:/scripts
#      - ./common/etc/yum.repos.d:/etc/yum.repos.d
#      - ./common/conf:/opt/modules/conf
#      - ./common/data/mvn:/root/.m2
#    entrypoint: /scripts/slave.sh
#    depends_on:
#      nexus:
#        condition: service_healthy
#    networks:
#      ambari-env-network:
#        ipv4_address: 172.20.0.5
#  centos4:
#    image: centos:centos8.4.2105
#    container_name: centos4
#    hostname: centos4
#    ports:
#      - "22226:22"
#      - "46379:6379"
#      - "46380:6380"
#      - "46381:6381"
#      - "46382:6382"
#      - "46383:6383"
#      - "46384:6384"
#      - "42181:2181"
#      - "42345:12345"
#    tty: true
#    privileged: true
#    volumes:
#      - ./scripts:/scripts
#      - ./common/etc/yum.repos.d:/etc/yum.repos.d
#      - ./common/conf:/opt/modules/conf
#      - ./common/data/mvn:/root/.m2
#      - /var/run/docker.sock:/var/run/docker.sock
#    #    entrypoint: /scripts/slave.sh
#    depends_on:
#      nexus:
#        condition: service_healthy
#    networks:
#      ambari-env-network:
#        ipv4_address: 172.20.0.7
  rocky8:
    image: rockylinux/rockylinux:8.10
    container_name: rocky8
    hostname: rocky8
    ports:
      - "85:80"
      - "22223:22"
      - "28080:8080"
      - "16379:6379"
      - "16380:6380"
      - "16381:6381"
      - "16382:6382"
      - "16383:6383"
      - "16384:6384"
      - "12181:2181"
      - "12345:12345"
    tty: true
    privileged: true
    volumes:
      - ./scripts:/scripts
      - ./common/etc/yum.repos.d/rocky8:/etc/yum.repos.d
      - ./common/conf:/opt/modules/conf
      - ./common/data/mvn:/root/.m2
      - ./common/data/rpm-package:/data/rpm-package
    entrypoint: /scripts/master_rocky8.sh
    depends_on:
      nexus:
        condition: service_healthy
    networks:
      ambari-env-network:
        ipv4_address: 172.20.0.8
  ubuntu22:
    image: ubuntu:22.04
    container_name: ubuntu22
    hostname: ubuntu22
#    ports:
#      - "85:80"
#      - "22223:22"
#      - "28080:8080"
#      - "16379:6379"
#      - "16380:6380"
#      - "16381:6381"
#      - "16382:6382"
#      - "16383:6383"
#      - "16384:6384"
#      - "12181:2181"
#      - "12345:12345"
    tty: true
    privileged: true
    volumes:
      - ./scripts:/scripts
      - ./common/etc/apt/ubuntu2204/sources.list.d:/etc/apt/sources.list.d
      - ./common/conf:/opt/modules/conf
      - ./common/data/mvn:/root/.m2
      - ./common/data/deb-package:/data/deb-package
    entrypoint: /scripts/master_ubuntu22.sh
    depends_on:
      nexus:
        condition: service_healthy
    networks:
      ambari-env-network:
        ipv4_address: 172.20.0.9
  kylin10:
    image: hxsoong/kylin:v10-sp3
    container_name: kylinv10
    hostname: kylin10
    platform: linux/amd64
    tty: true
    privileged: true
    volumes:
      - ./scripts:/scripts
      - ./common/etc/yum.repos.d/kylin-v10:/etc/yum.repos.d
      - ./common/conf:/opt/modules/conf
      - ./common/data/mvn:/root/.m2
      - ./common/data/rpm-package-kylin:/data/rpm-package
    entrypoint: /scripts/master_kylin10.sh
    depends_on:
      nexus:
        condition: service_healthy
    networks:
      ambari-env-network:
        ipv4_address: 172.20.0.10
  kylin10-arm:
    image: hxsoong/kylin:v10-sp3
    container_name: kylinv10-arm
    hostname: kylin10-arm
    platform: linux/arm64
    tty: true
    privileged: true
    volumes:
      - ./scripts:/scripts
      - ./common/etc/yum.repos.d/kylin-v10:/etc/yum.repos.d
      - ./common/conf:/opt/modules/conf
      - ./common/data/mvn:/root/.m2
      - ./common/data/rpm-package-kylin-arm:/data/rpm-package
    entrypoint: /scripts/master_kylin10_arm.sh
    depends_on:
      nexus:
        condition: service_healthy
    networks:
      ambari-env-network:
        ipv4_address: 172.20.0.11

#
#  mysql:
#    image: mysql:8.0
#    container_name: mysql8
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: dolphin
#      MYSQL_USER: dolphin
#      MYSQL_PASSWORD: dolphin
#    ports:
#      - "13306:3306"
#    networks:
#      ambari-env-network:
#        ipv4_address: 172.20.0.6
networks:
  ambari-env-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
